version: '2.4'

services:

    projetoarquiteturatarefa1:
        container_name: api-projetoarquiteturatarefa1
        environment:
            - VIRTUAL_HOST=api.projetoarquiteturatarefa1.local
            - PHP_VERSION_SHORT=8.2
            - PHPINI_OPEN_BASEDIR=/app
            - PHPFPM_LOG_LEVEL=debug
            - VIRTUAL_PORT=80
            - ALLOW_URL_FOPEN=On
            - LOG_FILE=api.log
            - PUBLIC_ROOT=public
            - NGINX_POLICY=Content-Security-Policy-Report-Only
            - NGINX_POLICY_VALUE=default-src self;
            - STATIC_URL=/static
            - STATIC_PATH=/app/static
        image: ghcr.io/parisprobr/server-tools:php-8.2
        hostname: api.projetoarquiteturatarefa1.local
        depends_on:
            - projetoarquiteturatarefa1-db
        command: bash -c 'chmod +x /root/scripts/start.sh; /root/scripts/start.sh'
        restart: always
        volumes:
            - ./:/app
            - ./storage/logs:/var/log/export
            - ./docker/scripts/start.sh:/root/scripts/start.sh
        env_file:
            - ./.env

    composer-projetoarquiteturatarefa1:
        image: composer:2.5
        network_mode: host
        container_name: composer-projetoarquiteturatarefa1
        user: "${UID}:${UID}"
        command: composer install
        volumes:
            - ./:/app
            - ${HOME}:${HOME}
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro

    projetoarquiteturatarefa1-db:
        container_name: projetoarquiteturatarefa1-db
        environment:
            MYSQL_ROOT_PASSWORD: kK123KFTah78dAiv
            MYSQL_DATABASE: projetoarquiteturatarefa1
            MYSQL_USER: projetoarquiteturatarefa1
            MYSQL_PASSWORD: kK123KFTah78dAiv
        image: mysql:5.7
        volumes:
            - ./database/mysql:/var/lib/mysql
        env_file:
            - ./.env

    phpmyadmin-projetoarquiteturatarefa1:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-projetoarquiteturatarefa1
        restart: on-failure
        links:
            - projetoarquiteturatarefa1-db
        environment:
            PMA_HOSTS: projetoarquiteturatarefa1-db
            VIRTUAL_HOST: mysql.projetoarquiteturatarefa1.local
        depends_on:
            - projetoarquiteturatarefa1-db
