version: '3'
services:
  # Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./docker/scripts/start.sh:/root/scripts/start.sh
    environment:
      SERVICE_NAME: app
    command: bash -c 'chmod +x /root/scripts/start.sh; /root/scripts/start.sh; php artisan migrate' 
    ports:
      - "8000:80"
    restart: always

  # Nginx
  webserver:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - app

  # Banco de Dados MySQL
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
